In [73]:
from tensorflow.keras.preprocessing.text import one_hot

In [74]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [75]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [76]:
## Define the vocabulary size
voc_size=10000

In [77]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [78]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3608, 8116, 9359, 6583],
 [3608, 8116, 9359, 1801],
 [3608, 8063, 9359, 7905],
 [6959, 7755, 1920, 4803, 1030],
 [6959, 7755, 1920, 4803, 7780],
 [3569, 3608, 7337, 9359, 702],
 [4345, 1221, 2884, 4803]]

In [79]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [80]:
import numpy as np


In [81]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3608 8116 9359 6583]
 [   0    0    0    0 3608 8116 9359 1801]
 [   0    0    0    0 3608 8063 9359 7905]
 [   0    0    0 6959 7755 1920 4803 1030]
 [   0    0    0 6959 7755 1920 4803 7780]
 [   0    0    0 3569 3608 7337 9359  702]
 [   0    0    0    0 4345 1221 2884 4803]]


In [82]:
## feature representation 
dim=10

In [83]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [84]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [85]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step


array([[[ 0.03620278,  0.02698367, -0.02114262, -0.0331744 ,
         -0.03734518,  0.0056858 , -0.03573382, -0.01561641,
         -0.03218102, -0.01054806],
        [ 0.03620278,  0.02698367, -0.02114262, -0.0331744 ,
         -0.03734518,  0.0056858 , -0.03573382, -0.01561641,
         -0.03218102, -0.01054806],
        [ 0.03620278,  0.02698367, -0.02114262, -0.0331744 ,
         -0.03734518,  0.0056858 , -0.03573382, -0.01561641,
         -0.03218102, -0.01054806],
        [ 0.03620278,  0.02698367, -0.02114262, -0.0331744 ,
         -0.03734518,  0.0056858 , -0.03573382, -0.01561641,
         -0.03218102, -0.01054806],
        [ 0.04296643, -0.04020362,  0.02653125, -0.03544461,
          0.03453709, -0.00716182,  0.04010833, -0.04177199,
          0.04562302,  0.01753545],
        [ 0.04978431,  0.01045841, -0.01855738,  0.02214422,
          0.01212386,  0.02299689, -0.02037993,  0.01147271,
          0.00721813, -0.00304886],
        [-0.04180706,  0.00782554,  0.03283267,  0.0

In [86]:
embedded_docs[0]

array([   0,    0,    0,    0, 3608, 8116, 9359, 6583], dtype=int32)

In [89]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>